sudo: required

services:
  - docker
  
language: cpp

compiler:
  - gcc

before_script:
  - docker build -t numeric_tools -f docker/dockerfile .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run --rm $ci_env numeric_tools