codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
    patch: off

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

ignore:
  - "/usr/include/**/*"        # ignore system lib
  - "/usr/local/include/**/*"  # ignore 3rd parties
  - "tests/src/platformio"     # don't know how to check coverage with platformio yet
  - "tests/testbench"
