#ifndef NMTOOLS_PLATFORMS_ARDUINO_HPP
#define NMTOOLS_PLATFORMS_ARDUINO_HPP

// some arduino doesn't have stl
#ifndef NMTOOLS_DISABLE_STL
#define NMTOOLS_DISABLE_STL
#endif // NMTOOLS_DISABLE_STL

#ifndef NMTOOLS_DISABLE_DYNAMIC_ARRAY
#define NMTOOLS_DISABLE_DYNAMIC_ARRAY
#endif // NMTOOLS_DISABLE_DYNAMIC_ARRAY

#endif // NMTOOLS_PLATFORMS_ARDUINO_HPP