FROM ubuntu:bionic

WORKDIR /opt/

## install sytem requirements
COPY requirements-apt.txt requirements.txt
RUN apt update && xargs apt install -y < requirements.txt

## install gtest
RUN git clone -b 'release-1.8.1' https://github.com/google/googletest.git \
    && cd googletest \
    && mkdir build && cd build \
    && cmake .. && make && make install

## install miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda

## install armadillo
RUN	wget http://sourceforge.net/projects/arma/files/armadillo-9.400.3.tar.xz && \
	tar xf armadillo-9.400.3.tar.xz && rm armadillo-9.400.3.tar.xz && \
	cd armadillo-9.400.3 && \
	mkdir build && cd build && \
	cmake .. && make && make install

## install eigen
RUN wget https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.tar.gz && \
	tar -zxvf 3.3.7.tar.gz && rm 3.3.7.tar.gz && \
	cd eigen-git-mirror-3.3.7 && mkdir build && cd build && cmake .. && make install

WORKDIR /app/numeric_tools/

COPY examples examples
COPY include include
COPY scripts scripts
COPY tests tests
COPY cmake cmake
COPY CMakeLists.txt CMakeLists.txt 

RUN mkdir build && cd build \
    && cmake .. && make

CMD ["bash","scripts/run_unit_tests.sh"]