name: android

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'


jobs:
  dockcross-android:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: android-arm-2020
            image: android-arm
            tag: 20201222-0217db3
          - name: android-arm64-2020
            image: android-arm64
            tag: 20201222-0217db3
          - name: android-x86-2021
            image: android-x86
            tag: 20210127-0c1f2c9
          - name: android-x86_64-2021
            image: android-x86_64
            tag: 20210127-0c1f2c9
          - name: android-arm-latest
            image: android-arm
            tag: latest
          - name: android-arm64-latest
            image: android-arm64
            tag: latest
          - name: android-x86-latest
            image: android-x86
            tag: latest
          - name: android-x86_64-latest
            image: android-x86_64
            tag: latest
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.image }}:${{ matrix.tag }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake ../.. && make -j2'
