name: arduino-platformio

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        test: []
        # TODO: re-enable arduino tests
        # test: [ufuncs, meta, utl]
        # TODO: re-enable manip & constexpr tests
        # test: [manip, ufuncs, meta, utl, constexpr]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: '3.8'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip --break-system-packages
        pip install --upgrade platformio --break-system-packages
    - name: Run PlatformIO CI
      run: |
        bash scripts/run_pio_test.sh -d arduino/${{ matrix.test }}