name: clang

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'


jobs:
  dockcross-clang:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/array/numeric-tests-doctest'
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/meta/numeric-tests-doctest-meta'
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/utl/meta/numeric-tests-utl-meta'
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/utl/array/numeric-tests-utl-array'
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/utl/utl/numeric-tests-utl'

  dockcross-clang-index:
    name: ${{ matrix.name }}-index
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang-werror.cmake -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_BUILD_INDEX_TESTS=ON ../.. && make -j2 VERBOSE=1 numeric-tests-index-doctest'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/index/numeric-tests-index-doctest'

  dockcross-clang-functional:
    name: ${{ matrix.name }}-functional
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang-werror.cmake -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_BUILD_FUNCTIONAL_TESTS=ON ../.. && make -j2 VERBOSE=1 numeric-tests-functional-doctest'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/functional/numeric-tests-functional-doctest'

  dockcross-clang-generic-ndarray:
    name: ${{ matrix.name }}-generic-ndarray
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake -DNMTOOLS_TESTING_GENERIC_NDARRAY=ON -DNMTOOLS_BUILD_VIEW_TESTS=ON ../.. && make -j2 VERBOSE=1 numeric-tests-view-doctest'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/view/numeric-tests-view-doctest'

  dockcross-clang-no-stl:
    name: ${{ matrix.name }}-no-stl
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake -DNMTOOLS_BUILD_VIEW_TESTS=ON -DNMTOOLS_TESTING_NOSTL=ON ../.. && make -j2 VERBOSE=1 numeric-tests-view-doctest'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/view/numeric-tests-view-doctest'

  dockcross-clang-no-stl-generic-ndarray:
    name: ${{ matrix.name }}-no-stl-generic-ndarray
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake -DNMTOOLS_TESTING_GENERIC_NDARRAY=ON -DNMTOOLS_BUILD_VIEW_TESTS=ON -DNMTOOLS_TESTING_NOSTL=ON ../.. && make -j2 VERBOSE=1 numeric-tests-view-doctest'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/view/numeric-tests-view-doctest'

  dockcross-clang-no-stl-generic-ndarray-eval:
    name: ${{ matrix.name }}-no-stl-generic-ndarray-eval
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake -DNMTOOLS_BUILD_META_TESTS=OFF -DNMTOOLS_BUILD_UTL_TESTS=OFF -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_TEST_ARRAY_EVAL=ON -DNMTOOLS_TESTING_GENERIC_NDARRAY=ON -DNMTOOLS_TESTING_NOSTL=ON ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/array/numeric-tests-doctest'

  dockcross-clang-generic-ndarray-eval:
    name: ${{ matrix.name }}-generic-ndarray-eval
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake -DNMTOOLS_BUILD_META_TESTS=OFF -DNMTOOLS_BUILD_UTL_TESTS=OFF -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_TEST_ARRAY_EVAL=ON -DNMTOOLS_TESTING_GENERIC_NDARRAY=ON -DNMTOOLS_TESTING_NOSTL=OFF ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/array/numeric-tests-doctest'
    
  dockcross-clang-constexpr-eval:
    name: ${{ matrix.name }}-constexpr-eval
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake -DNMTOOLS_BUILD_CONSTEXPR_TESTS=ON -DNMTOOLS_BUILD_META_TESTS=OFF -DNMTOOLS_BUILD_UTL_TESTS=OFF -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_TEST_ARRAY_EVAL=ON ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/constexpr/numeric-tests-constexpr-doctest'

  dockcross-clang-constexpr-no-stl-generic-ndarray-eval:
    name: ${{ matrix.name }}-constexpr-no-stl-generic-ndarray-eval
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake -DNMTOOLS_BUILD_CONSTEXPR_TESTS=ON -DNMTOOLS_BUILD_META_TESTS=OFF -DNMTOOLS_BUILD_UTL_TESTS=OFF -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_TEST_ARRAY_EVAL=ON -DNMTOOLS_TESTING_GENERIC_NDARRAY=ON -DNMTOOLS_TESTING_NOSTL=ON ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/constexpr/numeric-tests-constexpr-doctest'
  
  dockcross-clang-constexpr-generic-ndarray-eval:
    name: ${{ matrix.name }}-constexpr-generic-ndarray-eval
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DCMAKE_TOOLCHAIN_FILE=${PWD}/../../cmake/toolchains/clang.cmake -DNMTOOLS_BUILD_CONSTEXPR_TESTS=ON  -DNMTOOLS_BUILD_META_TESTS=OFF -DNMTOOLS_BUILD_UTL_TESTS=OFF -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_TEST_ARRAY_EVAL=ON -DNMTOOLS_TESTING_GENERIC_NDARRAY=ON -DNMTOOLS_TESTING_NOSTL=OFF ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/constexpr/numeric-tests-constexpr-doctest'