name: gcc-9

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
    - '*'

jobs:
  gcc-9:
    name: gcc-9
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: mkdir -p build/ && cd build/ && cmake .. && make -j1 VERBOSE=1
      - name: run tests
        run: |
          build/tests/array/numeric-tests-doctest
          build/tests/meta/numeric-tests-doctest-meta
          build/tests/utl/meta/numeric-tests-utl-meta
          build/tests/utl/array/numeric-tests-utl-array
          build/tests/utl/utl/numeric-tests-utl
  
  gcc-9-index:
    name: gcc-9-index
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: mkdir -p build/ && cd build/ && cmake -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_BUILD_INDEX_TESTS=ON .. && make -j1 VERBOSE=1 numeric-tests-index-doctest
      - name: run tests
        run: |
          build/tests/index/numeric-tests-index-doctest

  gcc-9-constexpr-eval:
    name: gcc-9-constexpr-eval
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: mkdir -p build/ && cd build/ && cmake -DNMTOOLS_BUILD_CONSTEXPR_TESTS=ON -DNMTOOLS_BUILD_META_TESTS=OFF -DNMTOOLS_BUILD_UTL_TESTS=OFF -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_TEST_ARRAY_EVAL=ON .. && make -j1 VERBOSE=1
      - name: run tests
        run: |
          build/tests/array/numeric-tests-doctest

  gcc-9-constexpr-generic-ndarray-eval:
    name: gcc-9-constexpr-generic-ndarray-eval
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: mkdir -p build/ && cd build/ && cmake -DNMTOOLS_BUILD_CONSTEXPR_TESTS=ON -DNMTOOLS_BUILD_META_TESTS=OFF -DNMTOOLS_BUILD_UTL_TESTS=OFF -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_TEST_ARRAY_EVAL=ON -DNMTOOLS_TESTING_GENERIC_NDARRAY=ON -DNMTOOLS_TESTING_NOSTL=OFF .. && make -j1 VERBOSE=1
      - name: run tests
        run: |
          build/tests/array/numeric-tests-doctest
  
  gcc-9-constexpr-no-stl-generic-ndarray-eval:
    name: gcc-9-constexpr-no-stl-generic-ndarray-eval
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: mkdir -p build/ && cd build/ && cmake -DNMTOOLS_BUILD_CONSTEXPR_TESTS=ON -DNMTOOLS_BUILD_META_TESTS=OFF -DNMTOOLS_BUILD_UTL_TESTS=OFF -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_TEST_ARRAY_EVAL=ON -DNMTOOLS_TESTING_GENERIC_NDARRAY=ON -DNMTOOLS_TESTING_NOSTL=ON .. && make -j1 VERBOSE=1
      - name: run tests
        run: |
          build/tests/array/numeric-tests-doctest
          