name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        test: [manip]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO CI
      run: |
        pio package pack --output nmtools.tar.gz
        cp nmtools.tar.gz tests/src/platformio/mbed/${{ matrix.test }}
        cd tests/src/platformio/mbed/${{ matrix.test }}
        mkdir -p lib
        cd lib
        tar -zxvf ../nmtools.tar.gz
        cd ..
        pio test -v --without-uploading --without-testing