name: windows-mingw

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'


jobs:
  dockcross-android:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: windows-static-x64-posix
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake ../.. && make -j2'

  dockcross-mingw-object:
    name: ${{ matrix.name }}-object
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: windows-static-x64-posix
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_BUILD_OBJECT_TESTS=ON ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/object/numeric-tests-object-doctest'

  dockcross-mingw-unroll:
    name: ${{ matrix.name }}-unroll
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - name: windows-static-x64-posix
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v3
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DNMTOOLS_TEST_ALL=OFF -DNMTOOLS_BUILD_UNROLL_TESTS=ON ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/unroll/numeric-tests-unroll-doctest'
