name: sycl

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'

jobs:
  hipsycl-clang14-omp-docker:
    name: hipsycl-clang14-omp-docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build docker
        run: |
          docker build . --tag nmtools:sycl-clang14-omp --file docker/sycl.dockerfile
      - name: run tests
        run: |
          docker run --rm nmtools:sycl-clang14-omp
  hipsycl-clang14-cuda-docker:
    name: hipsycl-clang14-cuda-docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build docker
        run: |
          docker build . --tag nmtools:sycl-clang14-cuda --file docker/sycl-cuda.dockerfile