name: web-wasm

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'


jobs:
  dockcross-wasm:
    name: ${{ matrix.name }}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - name: web-wasm-2020
            image: web-wasm
            tag: 20201222-0217db3
          - name: web-wasm-latest
            image: web-wasm
            tag: latest
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.image }}:${{ matrix.tag }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake ../.. && make -j2 VERBOSE=1'
      - name: run tests
        run: ./dockcross-${{ matrix.name }} node build/${{ matrix.name }}/tests/numeric-tests-doctest.wasm.js
