name: x86-simd

on:
  push:
    branches:
    - 'master'
    tags:
    - 'v*'
  pull_request:
    branches:
    - '*'


jobs:
  dockcross-x86-simd:
    name: ${{ matrix.name }}-x86-simd
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        include:
          - name: linux-x64
          - name: linux-x64-clang
    steps:
      - uses: actions/checkout@v2
      - name: setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./build/${{ matrix.name }}
          key: ${{ github.job }}-${{ matrix.name }}-${{ hashFiles('./**') }}
      - name: setup doctest
        run: bash scripts/download_doctest_header.sh -d include/
      - name: build
        run: ./dockcross-${{ matrix.name }} bash -c 'mkdir -p build/${{ matrix.name }} && cd build/${{ matrix.name }}/ && cmake -DNMTOOLS_BUILD_SIMD_TESTS=ON -DNMTOOLS_SIMD_TEST_ALL=ON -DNMTOOLS_TEST_ALL=OFF ../.. && make -j2 numeric-tests-simd-doctest VERBOSE=1'
      - name: run tests
        run: |
          ./dockcross-${{ matrix.name }} bash -c 'build/${{ matrix.name }}/tests/simd/numeric-tests-simd-doctest'